from parsing.anzu_lexer_desc import *

par_lexer = anzu_lexer

PAR_INPUT_VARIABLES = 'INPUT_VARIABLES'
PAR_OUTPUT_VARIABLES = 'OUTPUT_VARIABLES'
PAR_ASSUMPTIONS = 'ASSUMPTIONS'
PAR_GUARANTEES = 'GUARANTEES'

PAR_SECTIONS = (PAR_INPUT_VARIABLES, PAR_OUTPUT_VARIABLES, PAR_ASSUMPTIONS, PAR_GUARANTEES)